
###################################### Navigation english ######################################

[[main]]
identifier = "about"
name = "About"
url = "https://www.epiclines.nz/about/"
weight = 1

[[main]]
identifier = "contact"
name = "Contact"
url = "https://www.epiclines.nz/contact/"
weight = 2

[[main]]
identifier = "blog"
name = "Blog"
url = "https://www.epiclines.nz/blog/"
weight = 3







# footer menu
[[footer]]
name = "About"
url = "https://www.epiclines.nz/about/"
weight = 1

[[footer]]
name = "Contact"
url = "https://www.epiclines.nz/contact/"
weight = 2

[[footer]]
name = "Blog"
url = "https://www.epiclines.nz/blog/"
weight = 3

