[params]
  surfURL = "http://localhost:1314/surf/"
  motorhomeURL = "http://localhost:1315/motorhome/"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
  [[menu.main]]
    name = "Surf"
    url = "http://localhost:1314/surf/"
  [[menu.main]]
    name = "Motorhomes"
    url = "http://localhost:1315/motorhome/"
  [[menu.main]]
    name = "Blog"
    url = "/blog/"
  [[menu.main]]
    name = "About"
    url = "/about/"
  [[menu.main]]
    name = "Contact"
    url = "/contact/"

